pcloud/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
import allauth.urls

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^storage/', include('storage.urls')),
    url(r'^task/', include('task.urls')),
    url(r'^trash/', include('trash.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include(allauth.urls)),
    url(r'^get_dir_content$', views.get_dir_content, name='get_dir_content'),
]

task/urls.py
from django.conf.urls import url
from . import views

app_name = 'task'

urlpatterns = [
		
	url(r'^$', views.index, name='index'),
	url(r'^new$', views.create, name='create'),
	url(r'^update/(?P<pk>\d+)$', views.update, name='update'),
	url(r'^delete/(?P<pk>\d+)$', views.delete, name='delete'),
	url(r'^select/(?P<pk>\d+)$', views.select, name='select'),
]

trash/urls.py
from django.conf.urls import url
from trash import views

app_name = 'trash'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^show/(?P<pk>\d+)$', views.show, name='show'),
]

task/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from storage.models import Storage
from trash.models import Trash

# Create your models here.

class Task(models.Model):
	STATUS_NEW = 0
	STATUS_WAITING = 1
	STATUS_PROCESSING = 2
	STATUS_ACCEPTED = 3
	STATUS_ERROR = 4
	STATUSES = (
			(STATUS_NEW, 'New'),
			(STATUS_WAITING, 'Waiting'),
			(STATUS_PROCESSING, 'Processing'),
			(STATUS_ACCEPTED, 'Accepted'),
			(STATUS_ERROR, 'Error'),
		)
	name = models.CharField(max_length=255)
	status = models.IntegerField(choices=STATUSES, default=STATUS_NEW)
	is_selected = models.BooleanField(default=False)

	user = models.ForeignKey(User, related_name='tasks')
	
	MODE_REMOVE = 0
	MODE_TRASH = 1
	MODES = (
			(MODE_REMOVE, 'Remove'),
			(MODE_TRASH, 'Move to trash / Restore'),
		)
	mode = models.IntegerField(choices=MODES, default=MODE_TRASH)

	def select(self):
		if not self.status == self.STATUS_NEW:
			return
		active = Task.objects.filter(is_selected=True)
		if active:
			active.update(is_selected=False)
		self.is_selected = True
		self.save()

	def status_name(self):
		return self.STATUSES[self.status][1]

	def mode_name(self):
		return self.MODES[self.mode][1]

class SelectedStorageFiles(models.Model):
	path = models.CharField(max_length=255)
	task = models.ForeignKey(Task,
		on_delete=models.CASCADE,
		related_name="storage_files",
	)
	storage = models.ForeignKey(Storage, 
		on_delete=models.CASCADE)

class SelectedTrashFiles(models.Model):
	path = models.CharField(max_length=255)
	task = models.ForeignKey(Task,
		on_delete=models.CASCADE,
		related_name="trash_files"
	)
	trash = models.ForeignKey(Trash,
		on_delete=models.CASCADE)

trash/models.py
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User
from utils.models.item import Item

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Create your models here.
class Trash(models.Model):
	user = models.ForeignKey(User, related_name='trashes')
	path = models.CharField(max_length=256, default='')

	@classmethod
	def create(cls, user):
		trash = cls(user = user)
		trash.save()
		path = os.path.join(BASE_DIR, '.TRASH', user.username, trash.pk.__str__())
		trash.path = path
		trash.save()
		if not os.path.exists(path):
			os.makedirs(path)
		return trash

	def destroy_trash(self):
		item = Item.make_item_from_path(self.path)
		item.remove()
		self.delete()

task/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
	class Meta:
		model=Task
		exclude=["user"]

pcloud/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
import os

def home(request):
	data = []
	home_dir = os.path.expanduser('~/')
	names = os.listdir(home_dir)
	for name in names:
		new_path = os.path.join(home_dir, name)
		print new_path
		if os.path.isdir(new_path):
			is_dir = True
		else:
			is_dir = False
		data.append({'is_dir': is_dir, 'path': new_path, 'name': name})
	print data
	return render(request, 'home.html', {'files': data, 'current_dir': home}) 

def get_dir_content(request):
	data = []
	if request.method == 'GET':
		dest = request.GET['dest']
		try:
			names = os.listdir(os.path.expanduser(dest))
			for name in names:
				new_path = os.path.join(dest, name)
				if os.path.isdir(new_path):
					is_dir = True
				else:
					is_dir = False
				data.append({'is_dir': is_dir, 'path': new_path, 'name': name})
		except:
			pass
			# return render(request, 'storage/cannot_get_content.html')
	return render(request, 'home.html', {'files': data, 'current_dir': dest})

task/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Task
from .forms import TaskForm
import os
# Create your views here.

@login_required
def index(request):
	tasks = request.user.tasks.all()
	return render(request, 'task/index.html', { 'tasks' : tasks} )

@login_required
def create(request):
	form = TaskForm(request.POST or None)
	if request.method == 'POST' and form.is_valid():
		task = form.save(commit=False)
		task.user = request.user
		task.save()
		return redirect('task:index')		
	return render(request, 'task/new.html', {'form': form})

@login_required
def update(request, pk):
	task = get_object_or_404(Task, pk=pk)
	form = TaskForm(request.POST or None, instance=task)
	if request.method == 'POST' and form.is_valid():
		form.save()
		return redirect('task:index')
	return render(request, 'task/update.html', { 'form' : form, 'task' : task })

@login_required
def delete(request, pk):
	task = get_object_or_404(Task, pk = pk)
	if request.method == 'POST':
		task.delete()
		return redirect('task:index')
	return Http404('URL is does not exist')

@login_required
def show(request, pk, path):
	task = get_object_or_404(Task, pk = pk)
	path_user_dir = os.path.join(BASE_DIR, 'junk', request.user.username)
	if not os.path.exists(path_user_dir):
		os.makedirs(path_user_dir)
	path_in_task = os.path.join(path_user_dir, path)
	print path_in_task
	if not os.path.exists(path_in_task):
		raise Http404("Path does not exist")
	return redirect('task:index')

@login_required
def select(request, pk):
	task = get_object_or_404(Task, pk = pk)
	if request.method == 'POST':
		task.select()
		return redirect('task:index')
	return Http404('URL is does not exist')

trash/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from utils.models.item import Item

from .models import Trash
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Create your views here.

@login_required
def index(request):
	trashes = request.user.trashes.all()
	return render(request, 'trash/index.html', { 'trashes' : trashes } )

@login_required
def show(request, pk):
	trash = get_object_or_404(Trash, pk = pk)
	try:
		files = Item.make_item_from_path(trash.path).listdir()
	except Exception as e:
		return Http404('URL is does not exist')
	return render(request, 'storage/show.html', { 'files' : files })

templates/base.html
{% load static %}
{% load account %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>

        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
        

    </head>
    <body>

        {% include 'navbar.html' %}
        <div class="container" style="margin-top: 2em">
            {% block content %}
            {% endblock content %}
        </div>
       
        {% block javascript %}{% endblock %}
        <script src="{% static 'js/scripts.js' %}"></script>

    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
		<div class="storage-header col-lg-12">
			<h5>{{ current_dir }}</h5>
		</div>
		<div class="storage-body col-lg-10 col-lg-offset-2">
			{% for file in files %}
				{% if file.is_dir %}
					<div class="storage-element">
						<a href="{% url 'get_dir_content' %}?dest={{ file.path }}">{{ file.name }}</a>
					</div>
				{% else %}
					<div class="storage-element">{{ file.name }}</div>
				{% endif %}
			{% endfor %}
		</div>
	</div>

{% endblock %}

templates/navbar.html
{% load account %}
<!-- Static navbar -->
<nav class="navbar navbar-default bg-default" style="margin-bottom: 0" navbar-main">
	<div class="container">
		<div class="navbar-header">
		  	<a class="navbar-brand" href="/">Private cloud</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
		  	<ul class="nav navbar-nav">
				<li class="nav-elem"><a href="{% url 'storage:index' %}">Storage</a></li>
                <li class="nav-elem"><a href="{% url 'task:index' %}">Task</a></li>
                <li class="nav-elem"><a href="{% url 'trash:index' %}">Trash</a></li>
            </ul>
		  	<ul class="nav navbar-nav navbar-right">
		  		<li class="nav-elem dropdown">
		  			<a class="dropdown-toggle" data-toggle="dropdown" href="" aria-expanded="false">
	                    {% if user.is_active %}
	                        {% user_display user %}
	                    {% else %}
	                        Guest
	                    {% endif %}
	                    <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                    {% if user.is_active %}
                        <li>
                            <a href="#">
                                <span class="glyphicon glyphicon-user"></span>
                                <span class="glyphicon-class">
                                    Show Profile
                                </span>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{% url 'account_logout' %}">
                                <span class="glyphicon glyphicon-off"></span>
                                <span class="glyphicon-class">
                                    Logout
                                </span>
                            </a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url 'account_login' %}">
                                Login
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'account_signup' %}">
                                Sign Up
                            </a>
                        </li>
                    {% endif %}
                	</ul>

		  		</li>
		  	</ul>
		</div>

	</div>
</nav>

templates/task/index.html
{% extends 'base.html' %}
{% block content %}

<div class="col-lg-12">
	<h2>Storages</h2>
	<a href="{% url 'task:create'%}""><span class="glyphicon glyphicon-plus"></span>New Task</a>
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<th>Task Name</th>
					<th>Task Status</th>
					<th>Mode</th>
					<th>Is Selected</th>	
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
			{% for task in tasks %}
				<tr>
					<td>{{ task.pk }}</td>
					<td>{{ task.name }}</td>
					<td>{{ task.status_name }}</td>
					<td>{{ task.mode_name }}</td>
					<td>
					{% if task.is_selected %}
						<div class="btn btn-default">
							<span class="glyphicon glyphicon-ok"></span>
						</div>
					{% else %}
						<form method="post" action="{% url 'task:select' task.pk %}">
							{% csrf_token %}
							<button class="btn btn-default" type="submit">
								<span class="glyphicon glyphicon-remove"></span>
							</button>
						</form>
					{% endif %}
					</td>
					<td style="display: flex;">
						<a class="btn btn-default" href="{% url 'task:update' task.pk %}">
							<span class="glyphicon glyphicon-pencil"></span>
						</a>
						<form method="post" action="{% url 'task:delete' task.pk %}" >
							{% csrf_token %}
							<button class="btn btn-danger" type="submit">
								<span class="glyphicon glyphicon-trash"></span>
							</button>
						</form>
					</td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
</div>



{% endblock content %}

templates/task/new.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<div class="col-lg-12">
		<form method="post" action="{% url 'task:create' %}">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-primary" type="submit">Create</button>
		</form>
	</div>
</div>
{% endblock content %}

templates/task/update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<div class="col-lg-12">
		<h2>Edit Task {{ task.name }}</h2>
		<form method="post" action="{% url 'task:update' pk=task.pk %}">
			{% csrf_token %}
			{{ form.as_p }}
			<button class="btn btn-primary" type="submit">Save</button>
		</form>
	</div>
</div>


{% endblock content %}

templates/trash/index.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
	<div class="col-lg-12">
		<h2>Trashes</h2>
	</div>
	
	<div class="container">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>#</th>
					<th>Trash Name</th>
				</tr>
			</thead>
			<tbody>
			{% for trash in trashes %}
				<tr>
					<td>{{ trash.pk }}</td>
					<td><a href="{% url 'trash:show' trash.pk %}" class="btn">{{ trash.storage.name }}</a></td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
	
	</div>	
</div>

{% endblock content %}

templates/trash/show.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>Item Name</th>
				<th>Type</th>
				<th>Size</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
		{% for file in files %}
			<tr>
				<td>{{ file.name  }}</td>
				<td>{{ file.type }}</td>
				<td>{{ file.size }}</td>
				<td></td>
			</tr>
		{% endfor %}
		</tbody>
	</table>

</div>	
{% endblock content %}